#! /bin/bash -i

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
VARCONFIG=$DIR/VARIABLE_CONFIG

while read var val; do unset $var ; declare $var="$val" ; done < $VARCONFIG

if [ -z "$MAX_THREADS" ]; then
    MAX_THREADS=50
fi

usage() {
    echo "Usage: $0 [-u|d|c|l|i] [-r] [-t number] [-n name] /absolute_path/to/config_file " 1>&2
    echo "       -n <name for main job>, only works with -c" 1>&2
    echo "       -r is set, a report is generated (it's recommended to run -c or -l with -r)" 1>&2
    echo "       -d if set, a dryrun is performed" 1>&2
    echo "       -c if set, the whole thing is submitted to the cluster" 1>&2
    echo "       -i if set, only the conda environments will be installed, if they don't exist" 1>&2
    echo "       -u if set, the working directory will be unlocked (only necessary for crash/kill recovery)" 1>&2
    echo "       -l if set, the main snakemake thread and indivdual rules are run in the current terminal session" 1>&2
    echo "       -t <max_threads> maximum number of cpus to use for all rules at a time. Defaults to $MAX_THREADS for -c, and to 1 for -l. No effect on -r, -d or -u only." 1>&2
}

while getopts n:t:udlcrhi flag
do
    case $flag in
        i)
            INITIAL=true;;
        u)
            UNLOCK=true;;
        d)
            DRYRUN=true;;
        c)
            CLUSTER=true;;
        n)
            JNAME=$OPTARG;;
        r)
            REPORT=true;;
        l)
            LAPTOP=true;;
        t)
            THREADS=$OPTARG;;
        h)
            usage
            exit;;
        *)  
            echo "Unimplemented option: -$OPTARG" >&2 
            usage
            exit 1;;
        :) 
            echo "Missing option argument for -$OPTARG" >&2 
            usage
            exit 1;;
        ?)
            usage
            exit
             ;;
    esac
done

shift $((OPTIND-1))

if [ -z "$1" ]; then
    echo "missing input"
    usage
    exit 1
else
    CONFIGFILE=$1
fi


#if the file cannot be found
if [[ !  -e "$1" ]]; then
   echo "Configfile "$1" was not found."
   echo "Provide full path."
   exit 1
fi

if [ "$SNAKEMAKE_VIA_CONDA" = true ]; then
   CONDA_START="conda activate $DIR/conda/snakemake_env"
   CONDA_END="conda deactivate"
else
   CONDA_START=""
   CONDA_END=""
fi

if [ "$UNLOCK" = true ]; then
    echo "Unlocking working directory."
    eval $LOADING_MODULES
    eval $CONDA_START
    snakemake -j 1 -s $DIR/Snakefile --unlock --configfile $CONFIGFILE
    eval $CONDA_END
elif [ "$DRYRUN" = true ]; then
    echo "Dryrun."
    eval $LOADING_MODULES
    eval $CONDA_START
    if [ "$LOCK_SETTINGS" = true ]; then
        snakemake -j 1 -s $DIR/Snakefile --dryrun --config sessionName=$JNAME normalMem=$NORMAL_MEM_EACH bigMem=$BIGMEM_MEM_EACH bigCores=$BIGMEM_CORES settingsLocked=$LOCK_SETTINGS sessionKind=dryrun --configfile $CONFIGFILE
    else
        snakemake -j 1 -s $DIR/Snakefile --dryrun --config sessionName=$JNAME sessionKind=dryrun --configfile $CONFIGFILE
    fi
    eval $CONDA_END
elif [ "$INITIAL" = true ]; then
    echo "Initializing conda environments."
    eval $LOADING_MODULES
    eval $CONDA_START
    snakemake -j 1 -s $DIR/Snakefile --conda-create-envs-only --use-conda --conda-prefix $DIR/conda --local-cores 1 --configfile $CONFIGFILE
elif [ "$CLUSTER" = true ]; then
  START_TIME=`date +%s`
  NAMEHASH=`echo $START_TIME| cksum | awk '{print $1}'`
    if [ -z "$JNAME" ]; then
        JNAME="dadasnake_${NAMEHASH}"
    else
        JNAME="${JNAME}_${NAMEHASH}"
    fi
    if [ -z "$THREADS" ]; then
        THREADS=$MAX_THREADS
    fi
    echo "Submitting workflow to cluster"
    if [ "$REPORT" = true ]; then
        eval "${SUBMIT_COMMAND} $DIR/submit_scripts/dadasnake_withReport.sh $CONFIGFILE $VARCONFIG $JNAME $THREADS"
    else
        eval "${SUBMIT_COMMAND} $DIR/submit_scripts/dadasnake_withoutReport.sh $CONFIGFILE $VARCONFIG $JNAME $THREADS"
    fi
elif [ "$LAPTOP" = true ]; then
    echo "Running workflow in current session - don't use this setting except with small datasets (e.g. the test data set is okay)."
    START_TIME=`date +%s`
    NAMEHASH=`echo $START_TIME| cksum | awk '{print $1}'`  
    if [ -z "$JNAME" ]; then
        JNAME="dadasnake_${NAMEHASH}"
    else
        JNAME="${JNAME}_${NAMEHASH}"
    fi
    if [ -z "$THREADS" ]; then
        THREADS=1
    fi
    eval $LOADING_MODULES
    eval $CONDA_START
    if [ "$REPORT" = true ]; then
        snakemake -j $THREADS -s $DIR/Snakefile --keep-going --configfile $CONFIGFILE --config sessionName=$JNAME sessionKind=laptop --use-conda --conda-prefix $DIR/conda 
        snakemake -j $THREADS -s $DIR/Snakefile --configfile $CONFIGFILE --use-conda --conda-prefix $DIR/dada_env_common --report report.html 
    else
        snakemake -j $THREADS -s $DIR/Snakefile --keep-going --configfile $CONFIGFILE --config sessionName=$JNAME sessionKind=laptop --use-conda --conda-prefix $DIR/conda 
    fi
    eval $CONDA_END
elif [ "$REPORT" = true ]; then
    echo "Writing report."
    eval $LOADING_MODULES
    eval $CONDA_START
    snakemake -j 1 -s $DIR/Snakefile --report report.html --configfile $CONFIGFILE --use-conda --conda-prefix $DIR/conda
    eval $CONDA_END
else
    echo "Nothing was done, please give -u, -d, -r, -c, or -l to start anything."
fi


